version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  api:
    image: public.ecr.aws/b6y2o6i2/find-package-api
    container_name: api
    ports: 
      - 3333:3333
    environment:
      - SENTRY_DSN=https://2c390a8c532d436f8adbf19877d9c347@o1081829.ingest.sentry.io/6089751
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
    depends_on: 
      - redis
