import { Router } from "express";
import multer from "multer";
import uploadConfig from "../../../../config/upload";
import { ensureAuthenticated } from "../middlewares/ensureAuthenticated";
import { CreateUserController } from "../../../../modules/accounts/useCases/createUser/CreateUserController";
import { ensureAdmin } from "../middlewares/ensureAdmin";
import { GetUserController } from "../../../../modules/accounts/useCases/getUser/GetUserController";
import { TurnUserDriverController } from "../../../../modules/accounts/useCases/turnUserDriver/TurnUserDriverController";
import { ensureEnterprise } from "../middlewares/ensureEnterprise";
const usersRoutes = Router();
const uploadAvatar = multer(uploadConfig);
const createUserController = new CreateUserController();
const getUser = new GetUserController();
const turnUserDriverController = new TurnUserDriverController();
usersRoutes.post("/", createUserController.handle);
usersRoutes.get("/getUser/:id", getUser.handle);
usersRoutes.patch("/turnDriver/:user_id", ensureAuthenticated, ensureEnterprise, turnUserDriverController.handle);
export { usersRoutes };